### ISSUE TITLE
Error install pyblock

### ISSUE THREAD

**Issue by defanet** [hczhai/pyblock#1]
should I install block1.5.3 first before install pyblock?
I tried install pyblock independently, here I got error:

$ cmake .. -DBUILD_LIB=ON
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.5")
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found suitable version "3.8.5", minimum required is "3.8")
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pybind11'
-- PROJECT_NAME = block
-- PYTHON_VERSION_MAJOR = 3
-- PYTHON_VERSION_MINOR = 8
-- PYTHON_LIBRARIES = /usr/lib/x86_64-linux-gnu/libpython3.8.so
-- PYTHON_EXECUTABLE = /usr/bin/python3
-- PYTHON_EXECUTABLE_HINT =
-- PYTHON_INCLUDE_DIRS = /usr/include/python3.8
-- PYLIB_SUFFIX = .cpython-38-x86_64-linux-gnu.so
-- PYBIND_INCLUDE_DIRS =
-- BUILD_LIB = ON
-- Looking for sgemm_
-- Looking for sgemm_ - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Found BLAS: /usr/lib/x86_64-linux-gnu/libopenblas.so
-- Looking for cheev_
-- Looking for cheev_ - found
-- A library with LAPACK API found.
CMake Error at CMakeLists.txt:121 (FIND_PACKAGE):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/defanet/chemlib/pyblock/build/CMakeFiles/CMakeOutput.log".
See also "/home/defanet/chemlib/pyblock/build/CMakeFiles/CMakeError.log".

**Comment by hczhai** [comment]
`block 1.5.3` is not required for installing `pyblock`.
In fact, `pyblock` includes a revised copy of `block 1.5.3`.

The error is due to the library `eigen3` cannot be found in your system.
You can find a complete list of dependences here https://github.com/hczhai/pyblock/blob/master/.travis.yml

**Comment by defanet** [comment]
perfect, now I can use pyblock.
Thank you :)
